### ISSUE TITLE
exclude_additional not working?  just me?

### ISSUE THREAD

**Issue by HunterDG** [OleVik/grav-plugin-directorylisting#16]
I want to exclude the 'documentation' folder as follows:

page **route** displaying the tree: webpage.com/cms/safety (via `{{ directorylisting|raw }}` in the safety page **content** (in a ui-tab))
only directory **route** desired to be visible: webpage.com/cms/safety/docs
directory **route** I want to **exclude**: webpage.com/cms/safety/documentation
folder structure (Microsoft IIS): C:\inetpub\wwwroot\cms\user\pages\\**01.safety**\ (both "docs" and "documentation" here)
grav "home": webpage.com/cms

In other words I want to only see the "docs" directory in the tree, not the "documentation" directory.  

I've tried all sorts of variations - page-header and plugin global, relative and absolute, routable and physical, asterisks, "/" in various places (beginning of path, end of path, etc - like trying to figure out a complex .gitignore).  Seems nothing works.  What am I missing?  

```
title: Safety
directorylisting:
    exclude_main: true
    exclude_additional:
        - /safety/documentation
        - ./documentation
        - /documentation
        - documentation/
        - /documentation/
        - '*/documentation'
        - 'documentation/*'
        - '*/documentation/*'
        - cms/safety/documentation
        - cms/safety/documentation/
        - /safety/documentation
        - cms/01.safety/documentation/
        - cms/01.safety/documentation
        - documentation
    level: 2
    max_depth: 5
---
[ui-tabs]

[ui-tab title="Documentation"]

- [Documentation](./documentation)

{{ directorylisting|raw }}

[/ui-tab]
[/ui-tabs]

```
